# Home Page 
import streamlit as st

st.set_page_config(page_title="ICS Nepal Data Automation Studio", page_icon="📄", layout="wide")

# Custom CSS for a premium look
st.markdown("""
<style>
    .stApp, .main {
        background-color: #0b0f19;
        color: #e0e6ed;
        font-family: 'Inter', 'Roboto', sans-serif;
    }
    
    @keyframes floatIn {
        0% { opacity: 0; transform: translateY(30px); }
        100% { opacity: 1; transform: translateY(0); }
    }
    
    .floating-title {
        animation: floatIn 1.5s ease-out forwards;
        font-size: 3.5rem;
        font-weight: 800;
        background: linear-gradient(45deg, #00A8FF, #9D4EDD);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        margin-bottom: 0px;
        line-height: 1.2;
    }
    
    .sub-title {
        animation: floatIn 1.8s ease-out forwards;
        font-size: 1.3rem;
        color: #8c9bb0;
        margin-top: 10px;
        margin-bottom: 30px;
    }

    .stButton>button {
        width: 100%;
        height: 50px;
        border-radius: 8px;
        border: none;
        background: linear-gradient(90deg, #0052cc 0%, #00a8ff 100%);
        color: white;
        font-weight: bold;
        font-size: 16px;
        letter-spacing: 0.5px;
        transition: all 0.3s ease;
        box-shadow: 0 4px 15px rgba(0, 168, 255, 0.3);
    }
    .stButton>button:hover {
        background: linear-gradient(90deg, #0045ab 0%, #008fdb 100%);
        transform: translateY(-2px);
        box-shadow: 0 6px 20px rgba(0, 168, 255, 0.5);
        color: white;
    }
    
    .stMetric {
        background-color: #151a28;
        padding: 20px;
        border-radius: 12px;
        border: 1px solid #1f2937;
        box-shadow: 0 4px 6px rgba(0,0,0,0.3);
        transition: transform 0.3s ease;
    }
    .stMetric:hover {
        transform: translateY(-5px);
        border-color: #00A8FF;
    }
    
    [data-testid="stMetricValue"] {
        color: #00A8FF;
    }
    
    /* Footer styles */
    .footer-container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 20px 0;
        margin-top: 50px;
        border-top: 1px solid #1f2937;
        color: #6b7280;
        font-size: 0.9rem;
    }
    
    .footer-left {
        text-align: left;
    }
    .footer-right {
        text-align: right;
    }
    
    /* Ensure markdown dividing lines fit dark theme */
    hr {
        border-color: #1f2937 !important;
    }
</style>
""", unsafe_allow_html=True)

# Animated Header
st.markdown('<div class="floating-title">ICS Nepal Data Automation Studio</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-title">Enterprise-Grade Document Processing Engine</div>', unsafe_allow_html=True)

# Hero Section
st.markdown("---")
col1, col2 = st.columns([1.2, 1])

with col1:
    st.markdown("""
    ### 🚀 Transform Your Data Workflow
    
    Move beyond manual extraction. Our proprietary AI and spatial reconstruction models securely automate complex document processing, integrate instantly with your ecosystem, and scale unconditionally.
    
    **Infinite Capabilities:**
    - 📄 **Spatial OCR**: Preserves complex document layouts effortlessly
    - 🎯 **Advanced NLP**: Intelligently pinpoints crucial data metrics
    - 💾 **System Sync**: Immediate integration with enterprise databases
    - ⚡ **Zero-Latency Processing**: High-throughput automated pipelines
    """)
    
    if st.button("Initialize Processing Engine", use_container_width=True):
        st.switch_page("pages/1_OCR_Extractor.py")

with col2:
    # Using specific path where the image was generated by the AI
    st.image("E:\AI Projects\AS_Hackathon\codes\Img_1.png", use_container_width=True)

# Stats Section
st.markdown("---")
st.markdown("## 📊 Ecosystem Metrics")

col1, col2, col3 = st.columns(3)

with col1:
    st.metric("Documents Ingested", "100+")

with col2:
    st.metric("Processing Uplift", "93X")

with col3:
    st.metric("Spatial Accuracy", "95%")

# Call to Action
st.markdown("---")
st.markdown("## Experience the Future of Data")

if st.button("Launch Platform", key="bottom_launch"):
    st.switch_page("pages/1_OCR_Extractor.py")

# Advanced Footer matching the prompt request
st.markdown("""
<div class="footer-container">
    <div class="footer-left">Made with ❤️ by Manish, Chepal & Sankar.</div>
    <div class="footer-right">© 2026 ICS Nepal Data Automation Studio. All rights reserved.</div>
</div>
""", unsafe_allow_html=True)